### ISSUE TITLE
Shuffling the dataset

### ISSUE THREAD

**Issue by jinzita142857** [mertnakip/Recurrent-Trend-Predictive-Neural-Network#1]
Hello,
I have read through and implemented your article and code in its entirety. The results are excellent, and I am very grateful for your willingness to share this research. However, I have one question. With respect to time series data, you've shuffled the original samples after cleaning. I am wondering what is the motive behind this practice? I don't quite understand the reason for this procedure. Looking forward to your reply.
Best regards

**Comment by mertnakip** [comment]
Hello, 

I appreciate your interest in our research, and thank you for this question. In our fire detection paper, since the dataset was considerably small --in the number of fire experiments-- for deep learning (although it is one of the most completed datasets for fire detection), we performed shuffling to have training and test sets containing samples from different scenarios during cross-validation. Please recall that the input-output pairs are determined prior to shuffling to preserve the temporal dependencies. On the other hand, clearly, another approach can be to take each fire experiment file as a whole and perform cross-validation among fire experiment files instead of samples. When there are a sufficiently large number of fire experiments performed,  the latter case shall benefit more from the rTPNN architecture.

**Comment by jinzita142857** [comment]
I'm deeply grateful for the time you've taken to help me resolve this issue. Wishing you all the best.

**Comment by ronghuizhao** [comment]
> 我非常感谢您花时间帮助我解决这个问题。祝你一切顺利。

你好 可以分享一下代码吗？我自己实在跑不出来，非常感谢！！
