### ISSUE TITLE
Code description

### ISSUE THREAD

**Issue by ronghuizhao** [mertnakip/Recurrent-Trend-Predictive-Neural-Network#2]
Hello.
I have read and implemented your article and code in its entirety. Now there is a small question, please answer it. Run_CrossVal_rTPNN.py Line 31 failed_exp = [2, 15, 17]
bedroom_exp = np.array([3, 4, 5, 6, 21, 22, 23, 24, 25])
This label is inconsistent with the data set, is it necessary to re-label the data set? Thank you very much for your answer!!                          I report AssertionError when running the code: cannot find the length of the indexer
If it is a very simple question please forgive me, I am a novice to deep learning, thank you again!!

**Comment by mertnakip** [comment]
As you closed the issue, I think you solved the problem. Do you still need help?

**Comment by ronghuizhao** [comment]
> 当你关闭了问题时，我认为你解决了问题。您还需要帮助吗？

Yes, I still need your help. Thank you very much for taking the time to answer my questions

**Comment by mertnakip** [comment]
Hello, 

Sorry for not getting back to you sooner due to a busy schedule recently. 

First, let's note that the failed_exp list is not used at all, and the bedroom_exp list keeps the indices of files in the folder. It has no direct relationship with file names. 

In order to fix your issue, you may want to follow one of the following two ways: 

1. Change the list bedroom_exp according to the order of the files in your list. 
2. Update line 39 of ProcessData.py, which is **if file.endswith(".csv") and count in considered_files:**, to select files based on their names and keep those names in bedroom_exp.
